### ISSUE TITLE
m3_LoadModule fails with "unallocated linear memory" 

### ISSUE THREAD

**Issue by florianwinterstein** [wasm3/wasm3#137] opened 2020-05-12 22:31 UTC
Hello,

I modified the iOS example to load a simple OPA/rego function compiled into wasm.

The wasm file is 30561 bytes. m3_ParseModule appears to work but m3_LoadModule fails with "unallocated linear memory". 

Please take a look at the attached patch (added .txt because of github)
Thanks!

[opa_rego_test.patch.txt](https://github.com/wasm3/wasm3/files/4618762/opa_rego_test.patch.txt)

**Comment by vshymanskyy** [comment] 2020-05-29 16:37
This is because your module tries to import the memory. Wasm3 currently does not provide a way to import the memory (so this is duplicate of #110 )

**Comment by vshymanskyy** [comment] 2020-05-29 16:37
As a workaround, you can make your wasm module to initialize and export memory to the runtime.

**Comment by srenatus** [comment] 2021-04-26 07:34
😄 I've been working on OPA's Wasm module for the last few months, and just now tried using it with wasm3 to stumble upon the same thing. I'll see if there's something we can do on the OPA end! 

(@florianwinterstein if you're still using opa+wasm, I'd love to know more about your experience, and your use case. If you'd like, there's also a #wasm channel on the opa community slack now.)

**Comment by vshymanskyy** [comment] 2021-04-26 07:44
Could you attach your module binary please?

**Comment by srenatus** [comment] 2021-04-26 08:06
Sure thing! 👉 [policy.wasm.gz](https://github.com/wasm3/wasm3/files/6375282/policy.wasm.gz)

The entrypoint to evaluating it is `eval`, also see https://www.openpolicyagent.org/docs/edge/wasm/#exports

**Comment by vshymanskyy** [comment] 2021-04-26 11:55
@srenatus it should be easy to enable auto-importing the memory.
Just disable this if:
https://github.com/wasm3/wasm3/blob/96c750622f3edb281c261d05f36a1c2f37e5e100/source/m3_env.c#L329

But you'll have to implement the `OPA` interface: https://www.openpolicyagent.org/docs/v0.16.2/wasm/#imports
You can use `RawFunction` native interface, but I'd recommend to start with `pywasm3` for prototyping.

**Closed** 2021-04-26 12:08 UTC
Labels: discussion

**Comment by srenatus** [comment] 2021-04-26 12:10
@vshymanskyy thank you for those pointers 👏
