### ISSUE TITLE
stopping running WASI function calls

### ISSUE THREAD

**Issue by bacongobbler** [wasm3/wasm3#138] opened 2020-05-12 23:16 UTC
Hi everyone!

As I understand it, once a function is called, the main thread will be blocked until the function has run its course. This may lead to the current thread being blocked forever, in cases where the module runs into a infinite loop. It would be helpful to have the ability to stop a running function. Pausing and snapshotting the stack would be great, but we're really just looking for a way to stop a running function, graceful or not.

Looking at the function signatures, it would appear that once `m3_Call` or `m3_CallWithArgs` is invoked, the main thread is blocked, and a `M3Result` is returned.

https://github.com/wasm3/wasm3/blob/640bf0cc2671f1725234536c3cd4be50de6cc19e/source/wasm3.h#L215-L216

wasmtime recently implemented interrupt handles in https://github.com/bytecodealliance/wasmtime/pull/1490 to help alleviate this issue. Is there some way to accomplish this with wasm3? Is this what `m3_Yield` is for?

https://github.com/wasm3/wasm3/blob/640bf0cc2671f1725234536c3cd4be50de6cc19e/source/wasm3.h#L209

**Comment by soundandform** [comment] 2020-05-15 02:51
I plan to implement this soon. You'll be able to register a callback with the runtime. Loops will periodically invoke this callback, allowing the client to perform tasks, detected and escape from infinite loops, or potentially switch fibers.

m3_Yield on happens on function entry so isn't suitable for coping with inf. loops.

**Comment by vshymanskyy** [comment] 2020-06-02 21:13
Duplicate of #127

**Closed by vshymanskyy** 2020-06-02 21:13 UTC
