### ISSUE TITLE
cpp example fails

### ISSUE THREAD

**Issue by lzmartinico** [wasm3/wasm3#115] opened 2020-03-05 19:40 UTC
When I try to run wasm3_cpp_example, it fails with error `WASM3 error: function signature mismatch`. All spec tests are passing, but WASI tests are failing
```=== Simple WASI test ===
../build/wasm3 ./wasi/test.wasm cat ./wasi/0.txt
Result: <Empty Stack>

=== Simple WASI test (wasm-opt -O3) ===
../build/wasm3 ./wasi/test-opt.wasm cat ./wasi/0.txt
Result: <Empty Stack>

=== mandelbrot ===
../build/wasm3 ./benchmark/mandelbrot/mandel.wasm 128 4e5
100.00%
Elapsed time: 4919.19 ms
Result: <Empty Stack>

=== mandelbrot (doubledouble) ===
../build/wasm3 ./benchmark/mandelbrot/mandel_dd.wasm 128 4e5
100.00%
Elapsed time: 30427.68 ms
Result: <Empty Stack>

=== C-Ray ===
cat ./benchmark/c-ray/scene | ../build/wasm3 ./benchmark/c-ray/c-ray.wasm -s 128x128
Rendering took: 0 seconds (427 milliseconds)
Result: <Empty Stack>

=== smallpt (explicit light sampling) ===
../build/wasm3 ./benchmark/smallpt/smallpt-ex.wasm 16 64
Rendering (16 spp) 100.00%
Elapsed: 8474.6 ms
Result: <Empty Stack>

=== STREAM ===
../build/wasm3 ./benchmark/stream/stream.wasm
Error: memory allocation failed ()
FAIL: Output does not match pattern

=== Self-hosting ===
../build/wasm3 ./self-hosting/wasm3-fib.wasm
Result: <Empty Stack>

=== Brotli ===
cat ./benchmark/brotli/alice29.txt | ../build/wasm3 ./benchmark/brotli/brotli.wasm -c
Result: <Empty Stack>

=== CoreMark ===
../build/wasm3 ./benchmark/coremark/coremark-wasi.wasm
Result: <Empty Stack>

{'crashed': 0, 'failed': 1, 'timeout': 0, 'total_run': 10}
=======================
 FAILED: 1/10
=======================


```

**Comment by soundandform** [comment] 2020-03-06 05:21
The cpp example is now fixed. 
None of the desktop targets are showing your particular WASI failure. What platform are you building for?

**Comment by vshymanskyy** [comment] 2020-03-09 12:37
@lzmartinico please verify and close the issue

**Comment by vshymanskyy** [comment] 2020-03-09 13:50
I think this was resolved (as per our CI tests). Let us know if the issue is still there

**Closed by vshymanskyy** 2020-03-09 13:50 UTC

**Comment by lzmartinico** [comment] 2020-03-09 14:15
Yes, the cpp example was resolved, thank you. The WASI tests are still failing, I am trying to build for Ubuntu 16.04, using musl

**Comment by vshymanskyy** [comment] 2020-03-09 14:35
Sorry, musl is not explicitly supported (as for now).
But we would be glad for any PRs that fix musl-related issues.

**Comment by vshymanskyy** [comment] 2020-03-09 14:36
Please also note https://github.com/wasm3/wasm3/issues/79
I think `uvwasi` should support musl.
