### ISSUE TITLE
How could we get __heap_base in wasm3 vm from wasm file

### ISSUE THREAD

**Issue by everettjf** [wasm3/wasm3#122] opened 2020-03-15 16:18 UTC
javascript sample : 

```
        const pInput = instance.exports.__heap_base;
```

and more code below : 

```
        const memory = new WebAssembly.Memory({ initial: 2 });
        const response = await fetch('./copy.wasm');
        const bytes = await response.arrayBuffer();
        const { instance } = await WebAssembly.instantiate(bytes, {
          env: { memory }
        });

        // Text to copy.
        const text = 'Hello from JavaScript!';

        // Configure shared memory.
        const view = new Uint8Array(memory.buffer);
        const pInput = instance.exports.__heap_base;
        const pOutput = pInput + 1024;
```

ref: https://depth-first.com/articles/2019/10/16/compiling-c-to-webassembly-and-running-it-without-emscripten/

Thanks 😄

**Comment by everettjf** [comment] 2020-03-15 16:47
Emmmm, I got fields below : 

```
    u32                     importedGlobals;
    u32                     numGlobals;
    M3Global *              globals;
```

Maybe we could provide a function `v_FindGlobal`similar to `v_FindFunction`.

**Comment by vshymanskyy** [comment] 2020-03-16 14:30
Duplicate of #110

**Closed by vshymanskyy** 2020-03-16 14:30 UTC

**Comment by vshymanskyy** [comment] 2021-04-26 12:10
`m3_SetGlobal`, `m3_GetGlobal` API was added
