### ISSUE TITLE
No details on missing imported functions

### ISSUE THREAD

**Issue by jedisct1** [wasm3/wasm3#94] opened 2020-02-05 19:21 UTC
Hi there!

When an imported function is missing, the REPL simply outputs:

```text
Error: [Fatal] repl_call: missing imported function
Error: missing imported function ()
```

It would be super useful to know what exact imported function is missing.

**Comment by vshymanskyy** [comment] 2020-02-05 19:29
This is duplicate of #67 . Will get to this soon!

**Closed by vshymanskyy** 2020-02-05 19:29 UTC

**Comment by jedisct1** [comment] 2020-02-05 19:39
Woops, sorry for having missed the original issue.

**Comment by vshymanskyy** [comment] 2020-02-05 20:00
@jedisct1 it's OK. Sometimes it's hard to associate different issue descriptions and side-effects, even for core developers ;)

**Comment by cpeggg** [comment] 2020-04-12 14:45
May I ask is there any way to import the function that is in another wasm file by given args to wasm3 like --import <xxx.wasm>?
