### ISSUE TITLE
Unexpected value on the stack

### ISSUE THREAD

**Issue by erxiaozhou** [wasm3/wasm3#406] opened 2022-11-13 17:59 UTC
## Build commands
I compile the code with commit id fa18e9ece4dd45371deac69ded32838470a55c1b
Platform: Ubuntu 20.04
CPU: amd64
compile commands:
```
export CC=/usr/bin/clang-14
export CXX=/usr/bin/clang++-14
mkdir build
cd build
cmake -GNinja -DCMAKE_BUILD_TYPE=Debug .. 
ninja
```
execute:
[wasm3_stack_value1.zip](https://github.com/wasm3/wasm3/files/9997884/wasm3_stack_value1.zip)

wasm3 --func to_test <test_case_name>

## Expected behavior:
The value on the stack should be \x74\x00\x80\x7f

Actual behavior:
The value on the stack should be \x74\x00\xc0\x7f

Thank you.

**Comment by vshymanskyy** [comment] 2024-08-02 23:58
Duplicate of #405

**Closed by vshymanskyy** 2024-08-02 23:58 UTC
